backend:
  name: github
  repo: AdisonCavani/adison.me # Path to your GitHub repository
  branch: astro # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "src/public/static/images/uploads" # Media files will be stored in the repo
public_folder: "/static/images/uploads" # The src attribute for uploaded media

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/pages/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template
    fields: # The fields for each document, usually in front matter
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "@layouts/Post.astro",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Publish Date", name: "pubDate", widget: "datetime" }
      - { label: "Featured Image", name: "heroImage", widget: "image" }
      - { label: "Tags", name: "tags", widget: "list", min: 1 }
      - { label: "Body", name: "body", widget: "markdown" }
