name: Lighthouse CI
on:
  push:
    branches: [ master ]
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            https://adison.me/
          uploadArtifacts: true # Save results as an action artifacts
          temporaryPublicStorage: true # Upload lighthouse report to the temporary storage
